#!/bin/sh
[ -z "${BASH}" ] && exec "$0" "$@"

echo -n "composing $1 & $2 -> $3 ... "

(echo ; cat $3) | sed -f updates > correct
(echo ; java mixin.Main -tk $1.jak $2.jak) 2>&1 | sed -f updates > current

if diff -w -B correct current ; then
#    rm -f -r correct current || :
    echo succeeded
else
#    rm -f -r correct current || :
    echo failed
    exit 1
fi
