# Makefile

# Library source files
JAVA_SRC = NetworkObjectRmi.java OPFACRmi.java
JAVA_RMI_SRC = NetworkObjectRmi.java OPFACRmi.java
PACKAGENAME = F.Libraries.RmiStuff

# Use common rules
include ../../../../Makelib.mk

# End of file