#!/bin/bash

if [ -z "$BASH" ] ; then
    exec bash $0 $@
fi

echo "****************Mixin Path Declaration Regression Test***********"

bash regress-path combine \
&& bash regress-path comb.ine \
|| exit 1

bash regress-one Cons1 Ref1 CR11 \
&& bash regress-one Cons2 Ref1 CR21 \
&& bash regress-one Cons1 Ref2 CR12 \
&& bash regress-one Cons3 Ref3 CR33 \
|| exit 1

echo -e "\nMixin Path Declaration Regression Test succeeded."
