#!/bin/bash

#sed -f updates $1     | tr -s '\n\r' '\n' > correct
#sed -f updates $1.cpp | tr -s '\n\r' '\n' > current
cat $1 | tr -s '\n\r' '\n' > correct
cat $1.cpp | tr -s '\n\r' '\n' > current

if ! diff -w correct current ; then
   echo "failed diff on $1"
   exit 1
fi
