#!/bin/bash

[ -z "$BASH" ] && exec bash $0 $@

echo "******************* otherwise-inherit test ***************"
java jak2java.Main inherit.spec \
&& javac inherit.java \
&& java test2 > junk \
&& diff -b junk correct-inherited \
|| exit 1
