#!/bin/bash

[ -z "$BASH" ] && exec bash $0 $@

echo "************ Now testing WRFFE_MORTAR_FIST, WRFFE_ARTILLERY_FIST ****"
java jak2java.Main wrffe_fist.spec \
&& javac wrffe_fist.java \
&& java wrffe_mortar_fist > junk \
&& diff -b -b junk correct_fist \
|| exit 1
echo "************ Now testing WRFFE_MLRS_FIST ****"
java wrffe_mlrs_fist > junk \
&& diff -b -b junk correct_fomlrs \
|| exit 1
echo "************* Now testing WRFFE_MORTAR_FIST_ERROR ****"
java wrffe_mortar_fist_error > junk \
&& diff -b -b junk correct_m_f_error \
|| exit 1
