package fsats.guiIf;

public interface UIModel 
{
    /**
     * Called whenever the state of an Opfac changes.
     * Should be called after object construction to
     * set the initial state, and upon changes thereafter.
     * Should be called before any messageSent calls
     * generated by teh state change so that the UI can learn
     * about the new mission before seeing messages for it.
     */
    void stateChanged(Opfac state);

    /**
     * Called whenever an opfac sends a message.
     */
    void messageSent(Message message);
}
