#!/bin/bash

echo -n "translating $1 ... "

cat $1.correct | tr -s '\n\r' '\n' > correct

java bcjak2java.Main $1.jak || exit 1
cat $1.java | tr -s '\n\r' '\n' > current || exit 1
rm $1.java

if diff -b -B -w correct current ; then
    rm -f -r correct current || :
    echo succeeded
else
   rm -f -r correct current || :
    echo failed
    exit 1
fi
