#!/bin/bash

[ -z "$BASH" ] && exec bash $0 $@

echo "****************bcjak2java Tool Regression Test***********"

rm *.class *.java

bash regress-one c1 \
&& bash regress-one c2 \
&& bash regress-one c3 \
&& bash regress-one c4 \
&& bash regress-one c5 \
&& bash regress-one i1 \
&& bash regress-one i2 \
&& bash regress-one s3 \
|| exit 1

echo -n running s1-s2 test ... 

cp M.jjava M.java \
&& java bcjak2java.Main s1.jak s2.jak \
&& javac M.java s1.java s2.java \
&& java -cp "." s2 > junk \
&& diff -b junk correct-refined \
|| exit 1
echo succeeded

rm *.class *.java junk 

echo -e "\nbcjak2java tool Regression Test succeeded."
