#!/bin/bash
# $1 is the given model name

echo "Available layer(s) in $1 directory:"

x="stub"
y="refine" 
for dir in `ls $1`; 
do
  if [ -d $1/$dir ]; then
    if [ $dir != $x ]; then
    	if [ $dir != $y ]; then
				  # if there are .java files in directory, run jrename
         if ls $1/$dir/*.java 1>/dev/null 2>/dev/null ; then
            echo -n $dir " "
            cd $1/$dir
            jrename *.java
            cd ../..
         fi
    	fi
    fi
  fi
done;
