#!/bin/bash

echo -n "composing $1 & $2 -> $3 ... "

(echo ; java mixin.Main $1.jak $2.jak) 2>&1 | sed -f updates | tr -s '\n\r' '\n' > current
(echo ; cat $3) | sed -f updates  | tr -s '\n\r' '\n' > correct

if diff -w correct current ; then
#    rm -f correct current || :
    echo succeeded
else
#    rm -f correct current || :
    echo failed
    exit 1
fi
