#!/bin/bash

cp $1 $1.jak
cp $2 $2.jak
cp $3 $3.jak

echo -n "uncomposing $4 into $1 & $2 & $3..."

if ! java unmixin.Main $4 ; then
   echo "failed 'java unmixin.Main $4'"
   exit 1
fi

bash regress-test $1 \
&& bash regress-test $2 \
&& bash regress-test $3 \
|| exit 1

echo "succeeded"
