#!/bin/bash

echo -n "composing $1 & $2 & $3 -> $4 ... "

(echo ; java mixin.Main $1.jak $2.jak $3.jak) > output 2>&1
sed -f updates output | tr -s '\n\r' '\n' > current
(echo ; cat $4) | sed -f updates  | tr -s '\n\r' '\n' > correct

if diff -w correct current ; then
#    rm -f correct current || :
    echo succeeded
else
#    rm -f correct current || :
    echo failed
    exit 1
fi
