#!/bin/bash

[ -z "$BASH" ] && exec bash $0 $@

FAILURES=0

unset -v BEFORE
for DIR in cpy path class gpl interf sm local astgscope ; do
    [ -n "${BEFORE}" ] && echo -e "${BEFORE}" || BEFORE='\n'
    (cd "${DIR}" ; bash regress) || FAILURES=1
done

if ((FAILURES)); then
  echo -e "${BEFORE}mixin Regression Tests Completed with ERRORS"
else
  echo -e "${BEFORE}mixin Regression Tests Completed Successfully"
fi
